package cabinet.domain.model;

// Generated 2015-12-6 16:26:02 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Goodspropertyvalue generated by hbm2java
 */
public class Goodspropertyvalue implements java.io.Serializable {

	private int goodsPropertyValueId;
	private int cagetroyPropertyId;
	private int goodsId;
	private String shortStrValue="";
	private String longStrValue="";
	private Date dataChangeCreateTime;
	private Date dataChangeLastTime;
	private BigDecimal decimalValue=new BigDecimal(0);
	private boolean isDel;

	public Goodspropertyvalue() {
	}

	public Goodspropertyvalue(int goodsPropertyValueId, int cagetroyPropertyId,
			int goodsId, String shortStrValue, String longStrValue,
			Date dataChangeCreateTime, Date dataChangeLastTime,
			BigDecimal decimalValue, boolean isDel,int sortOrder) {
		this.goodsPropertyValueId = goodsPropertyValueId;
		this.cagetroyPropertyId = cagetroyPropertyId;
		this.goodsId = goodsId;
		this.shortStrValue = shortStrValue;
		this.longStrValue = longStrValue;
		this.dataChangeCreateTime = dataChangeCreateTime;
		this.dataChangeLastTime = dataChangeLastTime;
		this.decimalValue = decimalValue;
		this.isDel = isDel;
	}

	public int getGoodsPropertyValueId() {
		return this.goodsPropertyValueId;
	}

	public void setGoodsPropertyValueId(int goodsPropertyValueId) {
		this.goodsPropertyValueId = goodsPropertyValueId;
	}

	public int getCagetroyPropertyId() {
		return this.cagetroyPropertyId;
	}

	public void setCagetroyPropertyId(int cagetroyPropertyId) {
		this.cagetroyPropertyId = cagetroyPropertyId;
	}

	public int getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(int goodsId) {
		this.goodsId = goodsId;
	}

	public String getShortStrValue() {
		return this.shortStrValue;
	}

	public void setShortStrValue(String shortStrValue) {
		this.shortStrValue = shortStrValue;
	}

	public String getLongStrValue() {
		return this.longStrValue;
	}

	public void setLongStrValue(String longStrValue) {
		this.longStrValue = longStrValue;
	}

	public Date getDataChangeCreateTime() {
		return this.dataChangeCreateTime;
	}

	public void setDataChangeCreateTime(Date dataChangeCreateTime) {
		this.dataChangeCreateTime = dataChangeCreateTime;
	}

	public Date getDataChangeLastTime() {
		return this.dataChangeLastTime;
	}

	public void setDataChangeLastTime(Date dataChangeLastTime) {
		this.dataChangeLastTime = dataChangeLastTime;
	}

	public BigDecimal getDecimalValue() {
		return this.decimalValue;
	}

	public void setDecimalValue(BigDecimal decimalValue) {
		this.decimalValue = decimalValue;
	}

	public boolean getIsDel() {
		return this.isDel;
	}

	public void setIsDel(boolean isDel) {
		this.isDel = isDel;
	}


}
