package cabinet.domain.model;

// Generated 2015-12-6 16:26:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private int tagId;
	private String cname="";
	private String ename="";
	private int parentId;
	private Date dataChangeCreateTime;
	private Date dataChangeLastTime;
	private boolean isDel;
	private int sortOrder;
	private List<Tag> childen;

	public Tag() {
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public Date getDataChangeCreateTime() {
		return this.dataChangeCreateTime;
	}

	public void setDataChangeCreateTime(Date dataChangeCreateTime) {
		this.dataChangeCreateTime = dataChangeCreateTime;
	}

	public Date getDataChangeLastTime() {
		return this.dataChangeLastTime;
	}

	public void setDataChangeLastTime(Date dataChangeLastTime) {
		this.dataChangeLastTime = dataChangeLastTime;
	}

	public boolean getIsDel() {
		return this.isDel;
	}

	public void setIsDel(boolean isDel) {
		this.isDel = isDel;
	}
	
	public int getSortOrder() {
		return sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}
	
	
	public List<Tag> getChilden() {
		return childen;
	}
	public void setChilden(List<Tag> childen) {
		this.childen = childen;
	}

}
